name: 'Cache LFS files'
description: 'Downloads and caches all git LFS files.'

runs:
  using: 'composite'
  steps:
    - name: LFS Create File List
      run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id
      shell: bash

    - name: LFS Cache
      uses: actions/cache@v4
      with:
        path: .git/lfs/objects
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
        restore-keys: |
          ${{ runner.os }}-lfs-

    - name: LFS Pull
      run: git lfs pull
      shell: bash
