name: Test Linting

on: [push, pull_request, workflow_dispatch]

jobs:
  json:
    name: Perform Linting Tests (JSON)
    runs-on: ubuntu-latest

    # Only run on PRs if the source branch is on someone else's repo\
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}  
    steps:
      # Clones repository so it has access to the files
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Checks JSON for errors
      - name: Perform JSON Linting
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)
