name: Tests

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'
  workflow_dispatch:
  workflow_call:

jobs:
  test-json:
    name: Validate JSON
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Clones repository so it has access to the files
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Checks JSON for errors
      - name: Perform JSON Linting
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)
